### ISSUE TITLE
Node12 -> Node16

### ISSUE THREAD

**Issue by roykho** [AbleLincoln/push-to-sftp#2]
Hi there,

Now that the usage of Node12 is deprecated (see https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

Is there any plans to update the action to Node16?

**Comment by AbleLincoln** [comment]
Yes. I wasn't aware of this deprecation but should be an easy fix. I'll push it out today

**Comment by AbleLincoln** [comment]
Fixed with https://github.com/AbleLincoln/push-to-sftp/commit/ec23e57e7646a532c2087371fe2685d4bb085630
